### ISSUE TITLE
Create validator script to ensure packaged atlas meet certain criteria (maybe also with an option to display images for a visual check?)

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#217]
```[tasklist]
### Tasks
- [ ] https://github.com/brainglobe/bg-atlasgen/issues/97
- [ ] https://github.com/brainglobe/bg-atlasgen/issues/98
- [ ] https://github.com/brainglobe/brainglobe-atlasapi/issues/207
- [ ] https://github.com/brainglobe/bg-atlasgen/issues/100
- [ ] checking that files have expected format (internal columns, structure etc)
- [ ] https://github.com/brainglobe/bg-atlasapi/issues/173
- [ ] checking binarisation of annotation and template is the same
- [ ] check normals of all meshes are pointing outwards
- [ ] at least one mesh fits inside the root mesh
- [ ] https://github.com/brainglobe/brainglobe-atlasapi/issues/213
- [ ] Visual check that mesh files don't look bad (A lot of the mesh files look really bad (e.g. Waxholm), applying a small amount of non-warping smoothing makes a big difference)
- [x] Check all annotation IDs in some atlases have a corresponding area in the structure.json file
- [ ] check that atlas is in `asr` (this is a new design choice - please add to docs)
- [ ] https://github.com/brainglobe/bg-atlasgen/issues/82
```
