### ISSUE TITLE
Atlas generation refactoring

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#224]
- [ ] brainglobe/brainglobe-atlasapi#217
- [x] brainglobe/brainglobe-atlasapi#216
- [ ] Add a git commit hash metadata entry (also dependency version) brainglobe/brainglobe-atlasapi#228 
- [ ] brainglobe/brainglobe-atlasapi#218
- [ ] brainglobe/brainglobe-atlasapi#219
- [x] brainglobe/brainglobe-atlasapi#221
- [ ] brainglobe/brainglobe-atlasapi#220
- [x] brainglobe/brainglobe-atlasapi#222
- [ ] brainglobe/brainglobe-atlasapi#223

**Comment by adamltyson** [comment]
Closing this, because I'm not sure how useful this meta issue is, when the individual issues aren't very related.
