### ISSUE TITLE
GUI - roadmap

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainglobe-atlasapi#238]
GUI development roadmap

goal: write a pyqt GUI for atlas generation. Remove the need to actively write code during the atlas generation process.

## Steps:
- [ ] main functionality: create a pyqt GUI with main window and pop up windows. The main window can be used to enter basic data (e.g. atlas name) and to execute the different steps in the atlas generation process (e.g. extract meshes). The popup windows are dedicated to specific tasks like loading the reference image
- [ ] integrate with the atlas generation script: make sure that when all data is loaded it actually creates an atlas correctly
- [ ] testing? always hard with GUIs...
- [ ] CLI: create a terminal command for starting the gui (with [typer](https://github.com/tiangolo/typer))
- [ ] styling: make the GUI look nice and visually consistent with [brainrender's](https://docs.brainrender.info/usage/brainrender-gui)

## Considerations:
i. most pop up windows will be very similar, a base class can be used and shared across them
ii. useful text prompts (e.g. describing what is needed for a reference image) and display a summary (e.g. show the reference image loaded)
iii. the main window can have buttons, one for each step. The color of these buttons can be used to signal to the user which steps have been completed and which remains to be done. Same for the final atlas-generating button: it should be greyed out and unclickable until all required steps have been succesfully carried out

## info
Brainrender's GUI code, although messy, can be a useful reference point:
**main window & UI**
https://github.com/brainglobe/brainrender/blob/master/brainrender/gui/ui.py
https://github.com/brainglobe/brainrender/blob/master/brainrender/gui/style.py

**pop-up task specific windows**
https://github.com/brainglobe/brainrender/blob/master/brainrender/gui/widgets/add_regions.py

**add from file functionality**
https://github.com/brainglobe/brainrender/blob/master/brainrender/gui/apputils/add_from_file_control.py

** icons **
https://github.com/brainglobe/brainrender/tree/master/brainrender/gui/icons

**Comment by adamltyson** [comment]
@brainglobe/active-devs interested to know your thoughts on this issue? My hunch is that atlases have become so varied now that a GUI is unlikely to be flexible enough, and it would be too much work to build and maintain. 

I propose closing this issue and directing our efforts into making the script-based approach as straightforward as possible. 

In the future we could create an atlas generation (i.e. starting just from a template image or even raw data) GUI, but that should be a bit simpler as we don't need to provide as much flexibility.

**Comment by niksirbi** [comment]
I agree this feels far off into the future.
It hinges on us making the script-based atlas generation simpler and validated, and probably also implementing some version of #141. Only then a GUI may become possible. As things currently stand, there are too many branches on that decision tree, and a GUI would be hard to build, and probably of not much help.

So I think this is a cool idea, but should be tackled after the validation and atlas 2.0 bits.
